In [12]:
import torch

gru = torch.nn.GRU(128,128, batch_first=True)

b_size = 32
node_size = 8
l = 1
f = 128
x = torch.randn(b_size,node_size, l,f)

In [13]:
y = gru(x)

RuntimeError: input must have 3 dimensions, got 4

In [7]:
y[0].shape

torch.Size([32, 1, 128])

In [8]:
y[1].shape

torch.Size([1, 32, 128])

In [10]:
y[0].squeeze()

tensor([[ 3.1337e-01,  6.4220e-02,  3.4873e-01,  ..., -4.2120e-02,
         -1.1337e-01,  1.9362e-01],
        [-2.7143e-01,  2.2195e-01,  2.1811e-02,  ..., -1.3072e-01,
         -3.0616e-01, -3.2334e-01],
        [-7.6683e-02,  1.2467e-01, -2.3312e-01,  ..., -3.4779e-02,
         -2.0958e-01, -1.0525e-01],
        ...,
        [ 1.1092e-01,  4.8598e-01,  1.5335e-03,  ..., -2.9069e-01,
         -4.2438e-01,  2.4029e-02],
        [ 3.4068e-01,  1.1576e-01,  1.7575e-01,  ..., -4.2709e-01,
         -1.4523e-04, -1.1876e-03],
        [ 6.7855e-02,  1.9622e-01,  5.7706e-02,  ..., -1.3114e-01,
         -1.0218e-01, -2.1179e-01]], grad_fn=<SqueezeBackward0>)

In [11]:
y[1].squeeze()

tensor([[ 3.1337e-01,  6.4220e-02,  3.4873e-01,  ..., -4.2120e-02,
         -1.1337e-01,  1.9362e-01],
        [-2.7143e-01,  2.2195e-01,  2.1811e-02,  ..., -1.3072e-01,
         -3.0616e-01, -3.2334e-01],
        [-7.6683e-02,  1.2467e-01, -2.3312e-01,  ..., -3.4779e-02,
         -2.0958e-01, -1.0525e-01],
        ...,
        [ 1.1092e-01,  4.8598e-01,  1.5335e-03,  ..., -2.9069e-01,
         -4.2438e-01,  2.4029e-02],
        [ 3.4068e-01,  1.1576e-01,  1.7575e-01,  ..., -4.2709e-01,
         -1.4523e-04, -1.1876e-03],
        [ 6.7855e-02,  1.9622e-01,  5.7706e-02,  ..., -1.3114e-01,
         -1.0218e-01, -2.1179e-01]], grad_fn=<SqueezeBackward0>)

In [14]:
x.shape

torch.Size([32, 8, 1, 128])

In [16]:
x.reshape([-1,128]).shape

torch.Size([256, 128])

In [20]:
u = torch.randn(2,1)

v = torch.randn(2,2,4)

z = torch.cat([u,v], dim=2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [18]:
z.shape

torch.Size([2, 3, 4])

In [23]:
u.expand((2,2))

tensor([[-1.3711, -1.3711],
        [ 0.9083,  0.9083]])

In [24]:
o = torch.randn((32,8,8,1))
import torch.nn.functional as F
m = F.softmax(o,dim=-2)

In [25]:
m.shape

torch.Size([32, 8, 8, 1])

In [27]:
torch.sum(m[0,0])

tensor(1.)