In [22]:
data_path = '/workspace/data/data_folder/o2o/all_features/gifs_11/all_features_11.pkl'
import pickle as pkl
data = pkl.load( open(data_path, 'rb'))

In [25]:
data[0].

{'activity name': 'ParkParallel',
 'yt_id': 'em-Q2WCR73s',
 'frame no.': '4181',
 'frame_width': 1280,
 'frame_height': 720}

In [2]:
len(data)

2050

In [6]:
data[0].keys()
data[0]['i3d_feature_map'].shape

torch.Size([5, 12, 1024])

In [16]:
path = '/workspace/data/data_folder/o2o/gifs_11_features_vsgnet/_1_dgZ4-Ldw_1262_5.pt'

import torch
data2 = torch.load(path)


In [17]:
data2.keys()

dict_keys(['metadata', 'num_obj', 'bboxes', 'lr', 'mr', 'cr', 'object_pairs', 'num_relation', 'frame_deep_features', 'i3d_fmap'])

In [20]:
data2['frame_deep_features'].shape

torch.Size([11, 1024, 45, 80])

In [21]:
data2

{'metadata': {'activity name': 'FuelCar',
  'yt_id': '_1_dgZ4-Ldw',
  'frame no.': '1262',
  'frame_width': 1280,
  'frame_height': 720},
 'num_obj': 4,
 'bboxes': tensor([[[ 874.,  440., 1013.,  570.],
          [ 874.,  440., 1013.,  570.],
          [ 874.,  440., 1013.,  570.],
          [ 874.,  440., 1013.,  570.],
          [ 874.,  440., 1013.,  570.],
          [ 874.,  440., 1013.,  570.],
          [ 874.,  440., 1013.,  570.],
          [ 874.,  440., 1013.,  570.],
          [ 874.,  440., 1013.,  570.],
          [ 874.,  440., 1013.,  570.],
          [ 874.,  441., 1013.,  571.]],
 
         [[ 525.,  130., 1241.,  649.],
          [ 525.,  128., 1241.,  647.],
          [ 525.,  128., 1241.,  647.],
          [ 525.,  129., 1241.,  648.],
          [ 525.,  127., 1241.,  646.],
          [ 510.,  116., 1255.,  656.],
          [ 525.,  127., 1241.,  646.],
          [ 525.,  128., 1241.,  647.],
          [ 524.,  127., 1240.,  646.],
          [ 524.,  127., 1240.,  6

In [27]:
anno_path = '/workspace/work/misc/O2ONet/data/annotation.pkl'
data = pkl.load(open(anno_path, 'rb'))

In [19]:

import torch
from torch_geometric.nn import Sequential, GCNConv
gcn = GCNConv(32, 24)

batch = 20
max_num_obj = 15
feat_dim = 32

data = {}
data['node_feat'] = torch.randn((batch, max_num_obj, feat_dim))
data['num_obj'] = torch.randint(0, max_num_obj, size=(batch,))

data['bbox_scores'] = torch.randn((batch, max_num_obj, max_num_obj)) > 1

from copy import deepcopy as copy

data['bbox_scores_2'] = copy(data['bbox_scores'])
for i in range(batch):
    temp_ = data['num_obj'][i]
    data['bbox_scores_2'][i, temp_: , temp_: ] = False

batch_tensor, index1_tensor, index2_tensor = torch.where( data['bbox_scores_2'])

edge1_tensor = max_num_obj*batch_tensor+index1_tensor
edge2_tensor = max_num_obj*batch_tensor+index2_tensor
edge_index_tensor  = torch.cat( ( edge1_tensor.unsqueeze(0), edge2_tensor.unsqueeze(0) ))

node_feat_flattened = data['node_feat'].flatten(0,1)
embed = gcn(node_feat_flattened, edge_index_tensor)



In [20]:
embed.shape

torch.Size([300, 24])

In [16]:
new_edge_tensor.shape

torch.Size([2, 485])

In [10]:
torch.where(data['bbox_scores'])

(tensor([ 0,  0,  0,  ..., 31, 31, 31]),
 tensor([ 0,  0,  0,  ..., 13, 13, 14]),
 tensor([ 5,  7, 13,  ...,  8, 13, 14]))